channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - ipykernel
  - numpy
  - pandas
  - scikit-learn
  - nibabel
  - nilearn
  - matplotlib
  - scipy
  - seaborn
  - pytest
  - opencv
  - rpy2
  - r-base
  - r-glmnet
  - pip
  - pip:
      - torchvision
